### ISSUE TITLE
Warning: Yaf_Loader::autoload():

### ISSUE THREAD

**Issue by toxmc** [yantze/yaf#1]
Warning: Yaf_Loader::autoload(): Failed opening script /var/www/code/yaf/public/..//application/library/memcached.php: No such file or directory in /var/www/code/yaf/application/Bootstrap.php on line 64

Fatal error: Class 'memcached' not found in /var/www/code/yaf/application/Bootstrap.php on line 64????

**Comment by yantze** [comment]
这是因为你没有安装memcached这个php扩展，安装后就解决了

**Comment by toxmc** [comment]
安装了memcache这个扩展了，phpinfo()可以输出来

**Comment by toxmc** [comment]
好吧memcached和memcache不一样，了解了
